UNKNOWN = -1
WALL = 0
EMPTY = 1
NO_ANTS = 2
ENEMY_BASE = 3
BREAD = 4
GRASS = 5
TEAM_KARGAR = 6
TEAM_SARBAZ = 7

ENEMY_KARGAR = 8
ENEMY_SARBAZ = 9

ENTITIES = {TEAM_KARGAR, TEAM_SARBAZ, ENEMY_KARGAR, ENEMY_SARBAZ}
BUILDINGS = {WALL, ENEMY_BASE}
RESOURCES = {BREAD, GRASS}
EMPTIES = {EMPTY, NO_ANTS}